name: Feature request
description: Proposer une évolution
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: Besoin
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposition
